version: "3.8"

networks:
  my_network:
    driver: bridge

services:
  backend:
    container_name: objectdetection
    networks:
      - my_network
    build: ./od-backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"

  frontend:
    container_name: objectdetection
    networks:
      - my_network
    build: ./od-frontend
    restart: always
    ports:
      - "5500:80"
    depends_on:
      - backend

 