# Generated by Django 4.2.4 on 2023-08-20 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 19, 26, 22, 81995)),
        ),
    ]
