# Generated by Django 4.2.4 on 2023-08-20 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_picturemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 20, 29, 37, 759309)),
        ),
    ]
