# Generated by Django 4.2.4 on 2023-08-20 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_picturemodel_image_alter_picturemodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='text',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='x1',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='x2',
            new_name='origin_x',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='y1',
            new_name='origin_y',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='y2',
            new_name='width',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='score',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 23, 45, 55, 620275)),
        ),
    ]
