# Generated by Django 4.2.4 on 2023-09-05 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_picturemodel_result_image_picturemodel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 23, 50, 31, 231085)),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL),
        ),
    ]
